In [8]:
import numpy as np

def sigmoid(x):
    return 1/(1*np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

train_input = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])

train_output = np.array([[0,1,1,0]]).T

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights : ')
print(synaptic_weights)

for iteration in range(100000):
    input_layer = train_input
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = train_output - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training : ')
print(synaptic_weights)
    
print('Outputs after training : ')
print(outputs)

Random starting synaptic weights : 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training : 
[[ 6.09856189e+00]
 [-2.23756792e-03]
 [-6.09857040e+00]]
Outputs after training : 
[[0.00224609]
 [0.99775643]
 [0.99999149]
 [0.00224107]]
